# Generated by Django 5.0.7 on 2024-08-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="banner",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
