# Generated by Django 5.0.7 on 2024-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelevel",
            name="name",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("expert", "Expert"),
                    ("multiplication_by_5", "Multiplication by 5"),
                    ("division_by_5", "Division by 5"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
