# Generated by Django 5.0.7 on 2024-08-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_games", "0004_alter_gamescore_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescore",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
