# Generated by Django 5.0.7 on 2024-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("math_games", "0005_alter_gamescore_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamescore",
            name="score",
        ),
    ]
